---
- name: My Task
  # inventoryに定義されたホストまたはグループを指定
  hosts: web
  # become: true #rootユーザーで実行する
  roles:
    - role: common
      tags: common  # tagをつけることによって、指定のroleのみ実行することができる
    - role: web
      tags: web
